# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-04 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('lyricist', models.CharField(blank=True, max_length=255)),
                ('composer', models.CharField(blank=True, max_length=255)),
                ('arranger', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('by', models.CharField(blank=True, max_length=255)),
                ('tags', jsonfield.fields.JSONField(blank=True, default=[])),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='score.Album')),
            ],
        ),
    ]
